#!/usr/bin/env bash
# Builds app/src/main/assets/tlstore/catalog.tsv from scripts/tlstore/items.tsv.
#
#   scripts/tlstore/build-catalog.sh [path/to/termux-launcher-binaries/SHA256SUMS]
#
# Digests are never hand-written: a launcher: source is hashed from the file in
# this checkout, a binaries: source is looked up in the SHA256SUMS of the
# termux-launcher-binaries checkout passed as the first argument, and a plain
# http(s) source is downloaded once and hashed here (so building needs the
# network when one of those changes). pkg, bundle, fisher and npm-musl items
# carry no digest — apt, fisher and the npm registry's own sha512 are the check
# there. A source whose digest cannot be computed stops the build: an unpinned
# payload must never reach a phone. An item's picture is hashed the same way
# (it is always a launcher: source, or "-" when there is none) and its digest
# rides alongside it as its own column, the way the item's own source and
# digest columns already do.
#
# A plain URL must name an immutable revision — a tag or a commit — for the same
# reason a launcher: source does.
#
# The serial is YYYYMMDDNN and only ever moves forward; a second build on the
# same day gets NN + 1, because tlstore accepts a refreshed catalog only when
# its serial is higher than the one it already has.
#
# After building, sign it: scripts/tlstore/sign.sh
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
items="$here/items.tsv"
out="$repo/app/src/main/assets/tlstore/catalog.tsv"
sums="${1:-}"

[ -f "$items" ] || { echo "missing $items" >&2; exit 1; }

# --- serial ---------------------------------------------------------------
today="$(date +%Y%m%d)"
seq=1
if [ -f "$out" ]; then
    old="$(sed -n 's/^#.*serial=\([0-9][0-9]*\).*$/\1/p' "$out" | head -1)"
    if [ -n "$old" ] && [ "${old:0:8}" = "$today" ]; then
        seq=$((10#${old:8:2} + 1))
    fi
fi
serial="$(printf '%s%02d' "$today" "$seq")"

# --- digests --------------------------------------------------------------
declare -A binary_digest=()
if [ -n "$sums" ]; then
    [ -f "$sums" ] || { echo "no SHA256SUMS at $sums" >&2; exit 1; }
    while read -r digest name; do
        [ -n "${name:-}" ] || continue
        binary_digest["$name"]="$digest"
    done < "$sums"
fi

fetched="$(mktemp -d)"
trap 'rm -rf "$fetched"' EXIT

# source_digest <source> <name> — the digest of any launcher:/binaries:/http(s)
# source, whatever column it lives in. "-" (no source) passes straight through.
source_digest() {
    local source="$1" name="$2" path tag asset
    case "$source" in
        -) echo "-"; return 0 ;;
        launcher:*)
            path="${source#launcher:}"
            path="${path%@*}"
            [ -f "$repo/$path" ] || { echo "no such file: $path (for $name)" >&2; return 1; }
            sha256sum "$repo/$path" | cut -d' ' -f1
            ;;
        binaries:*)
            tag="${source#binaries:}"
            asset="${tag%@*}"
            if [ -z "$sums" ]; then
                echo "$name needs a SHA256SUMS argument for $asset" >&2
                return 1
            fi
            if [ -z "${binary_digest["$asset-aarch64"]:-}" ]; then
                echo "$asset-aarch64 is not in $sums (for $name)" >&2
                return 1
            fi
            echo "${binary_digest["$asset-aarch64"]}"
            ;;
        http://*|https://*)
            path="$fetched/$name.payload"
            if [ ! -f "$path" ]; then
                if ! curl -fsSL -o "$path" "$source"; then
                    rm -f "$path"
                    echo "$name: could not download $source" >&2
                    return 1
                fi
            fi
            sha256sum "$path" | cut -d' ' -f1
            ;;
        *)
            echo "$name: cannot compute a digest for $source" >&2
            return 1
            ;;
    esac
}

digest_for() {
    local kind="$1" source="$2" name="$3"
    case "$kind" in
        pkg|bundle|fisher|npm-musl) echo "-"; return 0 ;;
    esac
    source_digest "$source" "$name"
}

# --- rows -----------------------------------------------------------------
tmp="$(mktemp)"
trap 'rm -f "$tmp"; rm -rf "$fetched"' EXIT

{
    printf '# tlstore catalog\tserial=%s\n' "$serial"
    printf '# generated by scripts/tlstore/build-catalog.sh from scripts/tlstore/items.tsv — do not edit\n'
    printf '# name\tkind\tversion\tprefixes\tsource\tdigest\ttarget\trequires\toptions\tsummary\t'
    printf 'category\tupstream\tsetup\tstandfirst\tdoes1\tdoes2\tdoes3\ttry\tnotes\t'
    printf 'author\tlicence\tsize\tpicture\tpicture-digest\tdemo\tfeatured\treadme-skip\n'
} > "$tmp"

failed=0
count=0
featured_names=""
while IFS=$'\t' read -r name kind version prefixes source target requires options summary \
    category upstream setup standfirst does1 does2 does3 try notes \
    author licence size picture demo featured readme_skip || [ -n "${name:-}" ]; do
    [ -n "${name:-}" ] || continue
    case "$name" in \#*) continue ;; esac
    if [ -z "${readme_skip:-}" ]; then
        echo "$name: expected 25 tab-separated columns" >&2
        failed=1
        continue
    fi
    case "$name" in
        [a-z0-9]*) ;;
        *) echo "$name: a name is [a-z0-9][a-z0-9-]*" >&2; failed=1; continue ;;
    esac
    case "$kind" in
        pkg|binary|file|file-once|fisher|npm-musl|bundle) ;;
        *) echo "$name: unknown kind $kind" >&2; failed=1; continue ;;
    esac
    case "$category" in
        -|"Note taking"|Tools|AI) ;;
        *) echo "$name: unknown category $category" >&2; failed=1; continue ;;
    esac
    case "$setup" in
        0|1) ;;
        *) echo "$name: setup must be 0 or 1, not $setup" >&2; failed=1; continue ;;
    esac
    case "$featured" in
        0|1) ;;
        *) echo "$name: featured must be 0 or 1, not $featured" >&2; failed=1; continue ;;
    esac
    if [ "$featured" = 1 ]; then
        case " $featured_names " in
            *" $name "*) ;;
            *) featured_names="$featured_names $name" ;;
        esac
    fi
    if ! digest="$(digest_for "$kind" "$source" "$name")"; then
        failed=1
        continue
    fi
    if ! picture_digest="$(source_digest "$picture" "$name (picture)")"; then
        failed=1
        continue
    fi
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t' \
        "$name" "$kind" "$version" "$prefixes" "$source" "$digest" \
        "$target" "$requires" "$options" "$summary" >> "$tmp"
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t' \
        "$category" "$upstream" "$setup" "$standfirst" "$does1" "$does2" "$does3" "$try" "$notes" >> "$tmp"
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$author" "$licence" "$size" "$picture" "$picture_digest" "$demo" "$featured" "$readme_skip" >> "$tmp"
    count=$((count + 1))
done < "$items"

if [ "$failed" = 0 ] && [ "$(printf '%s' "$featured_names" | wc -w)" != 1 ]; then
    echo "exactly one item must be featured=1, found:$featured_names" >&2
    failed=1
fi

if [ "$failed" != 0 ]; then
    echo "refusing to write $out" >&2
    exit 1
fi

mkdir -p "$(dirname "$out")"
cp "$tmp" "$out"
chmod 644 "$out"
echo "wrote $out — $count items, serial=$serial"
echo "sign it with scripts/tlstore/sign.sh before it ships"
